/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package certamen2usmpoo2024701;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier.choque
 */
public class VentanaJFrameSacarPromedios extends javax.swing.JFrame {

    private AlmacenamientoAlumnos dbAlumnos;
    
    /**
     * Creates new form VentajaJFrameSacarPromedios
     */
    public VentanaJFrameSacarPromedios(AlmacenamientoAlumnos dbAlumnos) {
        this.dbAlumnos = dbAlumnos;
        initComponents();
        
        // Crea el modelo de datos para la tabla
    DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Alumno", "Nota1", "Nota2", "Nota3", "Promedio"}
    );

    // Llena la tabla con los datos de los alumnos
    List<Alumno> listaAlumnos = dbAlumnos.getDbRamAlumnos();
    for (Alumno alumno : listaAlumnos) {
        modeloTabla.addRow(new Object[]{alumno.getNombre(), alumno.getNota1(), alumno.getNota2(), alumno.getNota3(), alumno.ObtenerPromedio3Notas()});
    }

    // Establece el modelo de datos en la tabla
    tabla.setModel(modeloTabla);
    }
    
    private double calcularPromedioTotal() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
    int rowCount = modeloTabla.getRowCount();

    double sumaPromedios = 0;

    // Itera sobre todas las filas de la tabla
    for (int i = 0; i < rowCount; i++) {
        double promedio = (double) modeloTabla.getValueAt(i, 4); // La columna 4 es el promedio
        sumaPromedios += promedio;
    }

    // Calcula el promedio total dividiendo la suma de todos los promedios por el número de alumnos
    double promedioTotal = sumaPromedios / rowCount;

    return promedioTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        calcularPromFinal = new javax.swing.JButton();
        PromFinal = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ALUMNO Y SUS NOTAS GENERADAS AL AZAR");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Alumno", "Nota1", "Nota2", "Nota3", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        calcularPromFinal.setText("CalcularPromFinal");
        calcularPromFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPromFinalActionPerformed(evt);
            }
        });

        PromFinal.setText("0.0");

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(calcularPromFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PromFinal)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularPromFinal)
                    .addComponent(PromFinal))
                .addGap(18, 18, 18)
                .addComponent(cerrar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularPromFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPromFinalActionPerformed
        // Calcula el promedio de los promedios de todos los alumnos en la tabla
    double promedioTotal = calcularPromedioTotal();

    // Muestra el promedio total en el JLabel PromFinal
    PromFinal.setText(String.valueOf(promedioTotal));
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularPromFinalActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PromFinal;
    private javax.swing.JButton calcularPromFinal;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
